### ISSUE TITLE
pads do not show up on board

### ISSUE THREAD

**Issue by ghost** [palmerr23/t4-eagle-full#1]
when using your teensy  4.0 full the pads are not showing up on the board you design for the underpins/pads 24 -39 they show up in the board but when you show the board the pads dont show up
![openvfo_nextion_teensy_4 0](https://user-images.githubusercontent.com/8948159/77255878-fc034180-6c40-11ea-825b-9142794564d7.png)

**Comment by palmerr23** [comment]
Thanks for that. I'll take a look in the next few days. I've also made a
Simple version without VUSB - as I had a particularly complex PCB to build
with SPI/I2S/I2C all enabled at once and the pin was inthe way!

**Comment by ghost** [comment]
the issue is getting the pads into the right place . they show up when 
doing a schematic but when you goto a board view they are not there.  
This is the teensy 4.0 vfo and gpio breakout I have been working on so 
you see why I need it.

------ Original Message ------

**Comment by RichNeese** [comment]
here is the changed lib I am testing. I moved the pads from bottom to 
top


------ Original Message ------
From: "Richard Neese" <r.neese@gmail.com>
To: "palmerr23/t4-eagle-full" 
<reply@reply.github.com>
Sent: 3/23/2020 7:48:55 AM
Subject: Re[2]: [palmerr23/t4-eagle-full] pads do not show up on board 
(#1)

**Comment by RichNeese** [comment]
I have made 3 versions as I added pin holes for adding in the spring 
loaded connecters or headers .

but this puts the pins on the correct layer

------ Original Message ------
From: "Richard Neese" <r.neese@gmail.com>
To: "palmerr23/t4-eagle-full" 
<reply@reply.github.com>
Sent: 3/23/2020 8:19:27 AM
Subject: Re[3]: [palmerr23/t4-eagle-full] pads do not show up on board 
(#1)

**Comment by ghost** [comment]
here is a 4 in 1 update it has the basic ,breakout pads , pads and pins, 
and pins,

------ Original Message ------
From: "Richard Neese" <r.neese@gmail.com>
To: "palmerr23/t4-eagle-full" 
<reply@reply.github.com>
Sent: 3/23/2020 9:16:17 AM
Subject: Re[4]: [palmerr23/t4-eagle-full] pads do not show up on board 
(#1)

**Comment by palmerr23** [comment]
I've updated the libraries -  Two variants now one with the additional pads on the top, not the bottom of the board.

**Comment by ghost** [comment]
fixed overlapping pads eagle was complaining about


------ Original Message ------

**Comment by palmerr23** [comment]
Rich,

Do you want to send me your updated library and I'll merge your improvements into mine?

I'm happy to pick them up from your repo if that works better for you - but I noticed you haven't updated the files in a while.

**Comment by ghost** [comment]
will do
