### ISSUE TITLE
Pad 33 is named Pad 32

### ISSUE THREAD

**Issue by bleckers** [palmerr23/t4-eagle-full#2]
Just a quick one. Pad 33 is called Pad 32 and Pad 33 and 32 position connections are swapped.

**Comment by palmerr23** [comment]
Can't immediately find the problem - it is across all the libraries, or just one?

**Comment by bleckers** [comment]
It's in both the packages (top/bottom) as well as the connections in the FULL lbr file:

![connect](https://user-images.githubusercontent.com/12459597/81031692-6fe76980-8ed0-11ea-816a-b31bf10aeec9.png)

![connect2](https://user-images.githubusercontent.com/12459597/81031699-7249c380-8ed0-11ea-8d01-43ef153cc074.png)

**Comment by bleckers** [comment]
Created a PR for the fix.

**Comment by palmerr23** [comment]
PR now merged.

Thanks for the fix.
